### ISSUE TITLE
Error while trying to get entries with get-dsentries

### ISSUE THREAD

**Issue by rosaguta** [Devolutions/devolutions-server#113]
I'm recieving an error when trying to use the following command to get devolution entries `get-dsentries -VaultId 00000000-0000-0000-0000-000000000000` 

```powershell

isSuccess              : False
originalResponse       : 
Exception              : System.ArgumentException: Conversion from JSON failed with error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
                          ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
                            at Newtonsoft.Json.JsonTextReader.ParseValue()
                            at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
                            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                            at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                            at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                            at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
                            --- End of inner exception stack trace ---
                            at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
                            at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
                            at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing()
                            at System.Management.Automation.CommandProcessorBase.Complete()
ErrorMessage           : Conversion from JSON failed with error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
StandardizedStatusCode : 0
Body                   :

```
inside of exception:
```powershell
Message        : Conversion from JSON failed with error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
ParamName      : 
TargetSite     : System.Object ConvertFromJson(System.String, Boolean, System.Nullable`1[System.Int32], System.Management.Automation.ErrorRecord ByRef)
Data           : {}
InnerException : Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
                    at Newtonsoft.Json.JsonTextReader.ParseValue()
                    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
HelpLink       : 
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2147024809
StackTrace     :    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
```

i also tried  `get-dsentries -VaultId ([guid]::Empty)`

**Comment by rbstp** [comment]
Hello,

The Get-DSEntries has been deprecated. Instead, please use **Get-DSEntry -VaultID "vault id" -All**

Best regards,
Richard

**Comment by solipsist01** [comment]
Get-DSEntry -VaultID ([guid]::Empty) -all

It works, but the objects which are returned aren't that rich.

```
connectionSubType       : GoogleChrome
connectionType          : 5
group                   : redacted\redacted
id                      : e2ada7fd-83c1-4630-b266-85275a9bff64
imageName               : SampleServerBlue
keywords                : vmware
name                    : redacted.local
permissions             : @{canAdd=True; canCopyPassword=True; canDelete=True; canEdit=True; canEditHandbook=True; canDeleteHandbook=True; canEditSecurity=True; canExecute=True; canExport=True; canManageAttachments=True; canView=True; canViewAttachments=True; 
                          canViewConnectionHistory=True; canViewHandbook=True; canViewPassword=True; canViewServerLogs=True; canMove=True; canEditInformation=True; canViewSensitiveInformation=True}
supportSessionRecording : True

```

Basic things like host etc are missing. Is there a way to get a dump of all sessions and all it's members?

**Comment by erica-poirier** [comment]
Hello,

In fact the Get-DSEntry with the -All swtich doesn'T return that much information.

From the list obtained with this cmdlet, then it is possible to get the whole properties using the following command.
```
$result = Get-DSEntry -EntryId $id -AsRDMConnection
$xml = [XML]$result.Body.data.connectionInfo.data
```

You can also use the Convert-XMLToPSCUstomObject cmdlet to get an easier access to handle the object properties.

The reason why the -All switch doen't return that much information is because it is possible to get all entries from all vaults but that would return too much infomation and would be to heavy to handle.

Best regards,

**Comment by solipsist01** [comment]
Would it be possible to get at least host in that array? :) The output doesnt have to be the same as get-rdmsession from the remotedesktopmanager module, but host would be nice :)
